import mongoose from "mongoose";

const profileSchema = new mongoose.Schema({
  // Existing fields

  Psychics: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Psychics",
    required: true,
  }, birthDate: {
    type: Date,
    required: true,
  },
  category: {
    type: [String],
    required: true,
    enum: [
      "Medium",
      "Aura Reading",
      "Crystal Reading",
      "Pet Psychics",
      "Money Psychics",
      "Past Life",
      "Missing Person",
      "Astrologer",
      "Tarot Reader",
      "Numerologist",
      "Career Advice",
      "Runes Psychics",
      "Love Psychics",
      "Breakup Psychics",
      "Cheating Affairs",
      "Family Affairs",
      "Maritial",
      "Parents Children",
      "Empath Psychics",
      "Dream Analysis",
      "Clairvoyant",
      "Clarisentient",
    ],
  },
  primarySkills: {
    type: [String],
    required: true,
    enum: [
      "Medium",
      "Aura Reading",
      "Crystal Reading",
      "Pet Psychics",
      "Money Psychics",
      "Past Life",
      "Missing Person",
      "Astrologer",
      "Tarot Reader",
      "Numerologist",
      "Career Advice",
      "Runes Psychics",
      "Love Psychics",
      "Breakup Psychics",
      "Cheating Affairs",
      "Family Affairs",
      "Maritial",
      "Parents Children",
      "Empath Psychics",
      "Dream Analysis",
      "Clairvoyant",
      "Clarisentient",
     ],
  },
  allSkills: {
    type: [String],
    enum: [
      "Medium",
      "Aura Reading",
      "Crystal Reading",
      "Pet Psychics",
      "Money Psychics",
      "Past Life",
      "Missing Person",
      "Astrologer",
      "Tarot Reader",
      "Numerologist",
      "Career Advice",
      "Runes Psychics",
      "Love Psychics",
      "Breakup Psychics",
      "Cheating Affairs",
      "Family Affairs",
      "Maritial",
      "Parents Children",
      "Empath Psychics",
      "Dream Analysis",
      "Clairvoyant",
      "Clarisentient",
    ],
  },
  language: {
    type: [String],
    required: true,
    enum: [
      "English",
      "Spanish",
      "Mandarin",
      "Hindi",
      "French",
      "Arabic",
      "Bengali",
      "Russian",
      "Portuguese",
      "Urdu",
      "German",
      "Japanese",
      "Swahili",
      "Marathi",
      "Telugu",
      "Turkish",
      "Tamil",
      "Italian",
      "Korean",
      "Vietnamese",
    ],
  },
  chargesPerMin: {
    type: Number,
    required: true,
  },
  videoChargesPerMin: {
    type: Number,
    required: true,
  },
  reportCharges: {
    type: Number,
    required: true,
  },
  experienceYears: {
    type: Number,
    required: true,
  },
  dailyHours: {
    type: Number,
    required: true,
  },
  referredBy: {
    type: String,
    default: "",
  },
  workingOnOtherPlatform: {
    type: Boolean,
    required: true,
  },
},
{ timestamps: true }
);
const Profile = mongoose.model("Psy_Profile", profileSchema);

export default Profile;


